[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    https://github.com/ricardoquesada/bluepad32-arduino.git

lib_ignore =
    Bluepad32 for NINA-W10 boards