[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200

; Use the official Bluepad32 library distributed for Arduino
; instead of a custom framework package.
lib_deps =
  ricardoquesada/Bluepad32 @ ^4.2.0
